Add some type annotations
cvxgrp/cvxpy pull request #1298
Opened 2021-03-19 06:04 UTC by r-barnes

This begins to add Python type annotations to the codebase. These are mostly the low-hanging fruit as I didn't want to invest too much time without knowing your plan for this.

Type annotations are useful because tools like mypy and Pyre can use them to quickly detect, in almost real-time, whether a function or variable has been used improperly. They are available as of Python 3.5 (see [here](https://docs.python.org/3/library/typing.html)).

2021-03-19 11:48 UTC, rileyjmurray commented
Thanks for the PR @r-barnes! We're definitely on-board for getting more type annotations into cvxpy. The person who wrote our SCIP interface was actually very thorough with type annotations. I'll review this soon. In the meantime, you can check to see why our AppVeyor build failed.

2021-03-21 04:37 UTC, r-barnes commented
@rileyjmurray : All the tests pass! Ready for review.

2021-03-21 15:14 UTC, rileyjmurray requested changes
Hi @r-barnes, I've had a chance to go through your changes. It's clear that you put a lot of effort into this and I'd like to thank you for taking that initiative. On a quick note: it's a good idea to contact the cvxpy core developers before making changes of this scope. You can reach us by email, the Google Group, GitHub discussions, or just opening a GitHub issue. Contacting us first helps make sure your effort is well-spent and increases the likelihood that we can merge in your changes. Luckily, in your case the aren't really externalities to your changes so I think we should be okay.

I left a bit over 30 comments over the course of the review. One recurring comment involved the use of string literals in type annotations. Another recurring comment was that some return types were marked as ``int`` when they should be some kind of cvxpy Expression or Constraint.

A final point is that there are certain files where we might not want to do type annotations. For example, we might not want to do type annotations in unittests. That's just my gut feeling though. @SteveDiamond @akshayka what do you think?

2021-03-21 16:06 UTC, r-barnes commented on cvxpy/atoms/affine/binary_operators.py
> +def matmul(lh_exp, rh_exp) -> "MulExpression":
@rileyjmurray: A string literal denotes a forward reference: a type which is not yet defined at the time the type is used, such as when you refer to a class higher in a file and define the class lower down. (Search for "forward reference" [here](https://docs.python.org/3/library/typing.html) and [here](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html).) For newer versions of Python (3.7+, I think, with adequate checker support), the forward reference should resolve automatically (see [here](https://stackoverflow.com/questions/51629105/python-type-hint-given-as-a-string)).

2021-03-21 16:06 UTC, r-barnes commented on cvxpy/atoms/affine/diag.py
> +def diag(expr) -> Union["diag_mat", "diag_vec"]:
For forward references in pre-3.7 Python and an unknown number of later versions until it's deprecated.

2021-03-21 16:09 UTC, r-barnes commented on cvxpy/atoms/elementwise/huber.py
> +    def numeric(self, values) -> int:
Fixed.

2021-03-21 16:09 UTC, r-barnes commented on cvxpy/atoms/elementwise/kl_div.py
> +    def _grad(self, values) -> List[None]:
My bad: fixed.

2021-03-21 16:10 UTC, r-barnes commented on cvxpy/atoms/elementwise/kl_div.py
> +    def _grad(self, values) -> List[None]:
Although that return doesn't match the documentation "A list of SciPy CSC sparse matrices or None." -> an `Optional[List[csc_matrix_type]]` would match the documentation and might be cleaner.

2021-03-21 16:10 UTC, r-barnes commented on cvxpy/atoms/elementwise/power.py
> +    def copy(self, args=None, id_objects={}) -> "power":
Same answer as above.

2021-03-21 16:12 UTC, r-barnes commented on cvxpy/atoms/eye_minus_inv.py
> +def resolvent(X, s: float) -> float:
I think I'll drop the return for now. It looks to me like it should return a `eye_minus_inv`, but I'm not too familiar with how you've structured the mathematical overloads here.

2021-03-21 16:14 UTC, r-barnes commented on cvxpy/atoms/log_det.py
> +    def _domain(self) -> List[int]:
Fixed.

2021-03-21 16:16 UTC, r-barnes commented on cvxpy/atoms/matrix_frac.py
> +    def _domain(self) -> List[int]:
Fixed.

2021-03-21 16:17 UTC, r-barnes commented on cvxpy/expressions/constants/constant.py
> +    def constants(self) -> List["Constant"]:
Same as above.

2021-03-21 16:18 UTC, r-barnes commented on cvxpy/expressions/leaf.py
> +    def project_and_assign(self, val) -> None:
I think we're looking at the same place, but don't see a "return" statement.

2021-03-21 16:18 UTC, r-barnes commented on cvxpy/problems/objective.py
> +    def __neg__(self) -> "Maximize":
Same as above.

2021-03-21 16:19 UTC, r-barnes commented on cvxpy/problems/problem.py
> +    def __neg__(self) -> "Problem":
Same as above.

2021-03-21 16:19 UTC, r-barnes commented on cvxpy/problems/xpress_problem.py
> +    def __neg__(self) -> "XpressProblem":
Same as above.

2021-03-21 16:22 UTC, r-barnes commented on cvxpy/problems/xpress_problem.py
>      def __add__(self, other):
Unfortunately, that's not true. They can return `XpressProblem` or `NotImplemented`. Looking around I can't see any pattern matching `if.*NotImplemented`, so it seems as though you don't branch on the `NotImplemented`. If there's no branching, then the code must assume that the expected type is returned and will throw an error if it performs operations on `NotImplemented`.

In that case, why not `raise NotImplementedError()`? That ensures that the return type is consistent and flags cases where an unimplemented function is used early, rather than unexpectedly in up-stack code.

2021-03-21 16:22 UTC, r-barnes commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/normNuc_canon.py
> +def normNuc_canon(expr, args) -> Tuple[float, List[int]]:
Fixed, thanks.

2021-03-21 16:23 UTC, r-barnes commented on cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
> +                 formatted: bool=False) -> None:
Reverted.

2021-03-21 16:26 UTC, r-barnes commented on cvxpy/reductions/matrix_stuffing.py
> +def extract_mip_idx(variables) -> Tuple[List[Any], List[Any]]:
I can't follow the logic well here, but I do see `return [(vert_offset + idx,) for idx in ravel_idx]` which seems to imply lists of tuples.

2021-03-21 16:28 UTC, r-barnes commented on cvxpy/reductions/matrix_stuffing.py
> +    def invert(self, solution, inverse_data) -> Type[NotImplementedError]:
I think the appropriate approach is to annotate the function with the expected return value for the case in which the function were to be implemented and then `raise NotImpementedError()` from within the function. Raising an exception means that type checkers will accept the signature annotations without flagging an incorrect return value. See above, for more notes on `NotImplementedError` being difficult to work with as a return type.

2021-03-21 16:28 UTC, r-barnes commented on cvxpy/reductions/solution.py
> +def failure_solution(status, attr=None) -> "Solution":
Same as above.

2021-03-21 16:28 UTC, r-barnes commented on cvxpy/reductions/solution.py
> +    def copy(self) -> "Solution":
Same answer

2021-03-21 16:29 UTC, r-barnes commented on cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py
>  # that can be supplied to ecos.
Of course! Done.

2021-03-21 16:31 UTC, r-barnes commented on cvxpy/reductions/solvers/conic_solvers/scs_conif.py
> +def scs_psdvec_to_psdmat(vec, indices) -> int:
Fixed. Added types for the arguments as well.

2021-03-21 16:31 UTC, r-barnes commented on cvxpy/reductions/solvers/solving_chain.py
> +def construct_solving_chain(problem, candidates, gp: bool=False, enforce_dpp: bool=False) -> "SolvingChain":
Same answer as before

2021-03-21 16:31 UTC, r-barnes commented on cvxpy/reductions/solvers/solving_chain.py
> +    def prepend(self, chain) -> "SolvingChain":
Same

2021-03-21 16:31 UTC, r-barnes commented on cvxpy/reductions/solvers/utilities.py
> +def expcone_permutor(n_cones, exp_cone_order) -> int:
Fixed

2021-03-21 16:31 UTC, r-barnes commented on cvxpy/transforms/partial_optimize.py
> +def partial_optimize(prob, opt_vars=None, dont_opt_vars=None, solver=None) -> "PartialProblem":
Same answer

2021-03-21 16:33 UTC, r-barnes commented on cvxpy/transforms/scalarize.py
> +def weighted_sum(objectives, weights) -> int:
Fixed

2021-03-21 16:34 UTC, r-barnes commented on cvxpy/utilities/scopes.py
> +def dpp_scope() -> Generator[None, None, None]:
`Iterator[None]` is also semantically and syntactically correct.

2021-03-21 16:35 UTC, r-barnes commented on cvxpy/utilities/shape.py
> +from typing import Tuple
My bad; removed.

2021-03-21 16:40 UTC, r-barnes commented
@rileyjmurray : I've replied to your comments.

The use of string literals as type annotations covers the case of forward references. Future versions of Python will deprecate this pattern in favour of proactively resolving the types automatically. Older versions (3.5-3.7) require the strings since they (I infer) do only a single pass for type resolution, which is, after all, meant to be a quicker check on correctness than running a test suite.

A recurring pattern I see in the code is the use of `return NotImplemented` or `return NotImplementedError`. As far as I can tell the code never branches on or checks for this return type. It seems to me it would be better to raise an exception if a not-implemented function is used than to design the function's interfaces around passing `NotImplemented` around.

2021-03-22 01:25 UTC, r-barnes commented
All checks are again passing.

2021-03-28 18:59 UTC, SteveDiamond commented
> @rileyjmurray : I've replied to your comments.
> 
> The use of string literals as type annotations covers the case of forward references. Future versions of Python will deprecate this pattern in favour of proactively resolving the types automatically. Older versions (3.5-3.7) require the strings since they (I infer) do only a single pass for type resolution, which is, after all, meant to be a quicker check on correctness than running a test suite.
> 
> A recurring pattern I see in the code is the use of `return NotImplemented` or `return NotImplementedError`. As far as I can tell the code never branches on or checks for this return type. It seems to me it would be better to raise an exception if a not-implemented function is used than to design the function's interfaces around passing `NotImplemented` around.

I've looked into the ``return NotImplemented`` pattern, and I agree with you it should raise an exception instead. Let's save that change for another PR though.

Also, @r-barnes what kind of tooling are you using to get these type annotations? I'm a bit worried about maintaining them as we change the code.

2021-03-28 22:41 UTC, r-barnes commented
> I've looked into the return NotImplemented pattern, and I agree with you it should raise an exception instead. Let's save that change for another PR though.

Noted; I've put up #1310 to address that.

> Also, @r-barnes what kind of tooling are you using to get these type annotations? I'm a bit worried about maintaining them as we change the code.

There are two tools I'm aware of that interface with type annotations: [mypy](https://mypy.readthedocs.io/en/stable/) and [Pyre](https://pyre-check.org/), though of the two I have much more experience with Pyre. The purpose of both is to ensure that functions receive and return what they say they should. This is typically something they're able to do in real-time with the effect of (in my experience) decreasing maintenance burdens by quickly and clearly highlighting issues that would otherwise be caught as (potentially) opaque exceptions by a test suite.

Pyre, in particular, has an inference mode that is able to generate code mods that add types which can be unambiguously inferred from context. The commits in this PR were largely generated this way, though I've also hand-checked most of the changes. Unfortunately, inference alone cannot fill in all the types (as in ambiguous cases such as returning `NotImplemented`), so some manual work is usually necessary.

I don't know of an automated tool for _removing_ type annotations if you find them to be an unhelpful maintenance burden later, but you could simply ignore them since they are not checked/enforced at runtime and so do not otherwise affect how your code is run.

2021-03-29 00:30 UTC, SteveDiamond commented
Thanks @r-barnes that's very clarifying! I don't have too much experience with type checking in Python, so the pointers to mypy and Pyre are helpful. Hopefully changing the NotImplemented return types to exceptions will simplify some of the type signatures. Anyway, this is a great PR and I hope we can merge it in soon.

2021-03-29 00:58 UTC, r-barnes commented
I've rebased onto the latest master to resolve the merge conflict that had come up.

> Thanks @r-barnes that's very clarifying! I don't have too much experience with type checking in Python, so the pointers to mypy and Pyre are helpful. Hopefully changing the NotImplemented return types to exceptions will simplify some of the type signatures. Anyway, this is a great PR and I hope we can merge it in soon.

To make a couple of the engineering considerations in that thought more explicit:
* For someone unfamiliar with your code looking to modify it, type annotations quickly answer the question, "What does this take and what does it return?" In a lot of what we might think of as quality code, this is expressed in the form of docstrings or descriptive variable names, but neither of these mechanisms are enforcing. So your maintenance burden without type annotations in this case is always remembering to update the docstrings appropriately or figuring out intuitive names for variables that describe both their purpose ("I take a range") as well as their type ("I take a range of integers"). With type annotations you can focus docstrings on higher-level statements and variables can be solely conceptual; mypy and Pyre can also ensure that the annotations are consistent.
* In some of the places I've worked we've had millions of lines of Python being used by disparate teams. Type annotations help those teams use libraries correctly and help library authors avoid changes that would break downstream code. (Not possible for cvxpy, of course, since it's not part of such a mega-repo.) In these environments test suites can take _hours_ to run (and there's usually minimal documentation). So having fast correctness checks can be an enormous productivity boost.

Let me know if there's anything I can do for this PR.

2021-03-29 01:31 UTC, rileyjmurray commented on cvxpy/atoms/elementwise/kl_div.py
> +    def _grad(self, values) -> List[None]:
@r-barnes I've looked at all other conversations and I think this PR is good to go. If you'd like, you're welcome to change this to use ``Optional[List[csc_matrix_type]]`` (or whatever the syntactically correct statement would be) as you suggest. Regardless, I'll merge this PR in tomorrow morning.

2021-03-29 02:30 UTC, r-barnes commented on cvxpy/atoms/elementwise/kl_div.py
> +    def _grad(self, values) -> List[None]:
@rileyjmurray : I think I'd prefer to wait on that update. The documentation indciates "A list of SciPy CSC sparse matrices or None." but if we look at the code `kl_div.elemwise_grad_to_diag` gets called and that is returning `sp.dia_matrix`, which seems distinct from a CSC matrix. So it seems like a lot to untangle to include it in this PR.

2021-03-29 02:46 UTC, rileyjmurray commented on cvxpy/atoms/elementwise/kl_div.py
> +    def _grad(self, values) -> List[None]:
@r-barnes fair enough!

2021-03-29 02:46 UTC, merged